config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#home'
  get '/home/about', to: "homes#about"
  get '/search', to: 'users#search'
  get '/sort', to: 'books#index', as: :sort
  get 'chat/:id', to: 'chats#show', as: :chat
  get 'tags/:tag', to: 'books#index', as: :tag
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: "Relationship",
                    foreign_key: "follower_id",
                    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                    foreign_key: "followed_id",
                    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  attachment :profile_image, destroy: false

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  validates :prefecture_code, :address_city, :address_street, presence: true
  validates :postal_code, format: { with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}$|^\d{5}$|^\d{7}\z/ }

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "0"
      if how_search == "0"
        User.where(['name LIKE ?', "#{search}"])
      elsif how_search == "1"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "2"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "3"
        User.where(['name LIKE ?', "%#{search}%"])
      else
        User.none
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        ThanksMailer.send_mail(current_user).deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :ranking_books, except: [:show]

  def index
    @book = Book.new
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    if params[:sort]
      @books = Book.where(user_id: @user.id).order(sort_column + ' ' + sort_direction).page(params[:page])
    else
      @books = @user.books.page(params[:page])
    end

    @ranking_books = Book.my_rank(current_user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to @user
    else
      render "edit"
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page])
  end

  def followers
    @titlt = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page])
  end

  def search
    @user_or_book = params[:option]
    @how_search = params[:choice]
    if @user_or_book == "0"
      @users = User.search(params[:search], @user_or_book, @how_search)
    else
      @books = Book.search(params[:search], @user_or_book, @how_search)
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def address_params
    params.require(:user).permit(:postal_code, :prefecture_name, :address_city, :address_street, :address_building)
  end
end

# class Users::RegistrationController < Devise::RegistrationController
#   def create
#     respond_to do |format|
#       if @user.save
#         ThanksMailer.compelete_mail(@user).delivar_now
#         format.html { redirect_to @user, notice: 'User was successfully created' }
#         format.json { render :show, status: :created, location: @user }
#       else
#         format.html { render :new}
#         format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
#   end
# end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<td>following: <%= user.following.count %></td>
<td>followers: <%= user.followers.count %></td>
<td>
  <% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= render 'unfollow', user: user %>
    <% else %>
      <%= render 'follow', user: user %>
    <% end %>
  <% end %>
</td>

app/views/users/_follow_users.html.erb
<% provide(:title, @title)%>
<h2><%= yield(:title) %> Users</h2>

<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colpsan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, class: "image-square, pull-left profile-img", fallback: "no_image.png" %></td>
            <td><%= user.name %></td>
            <%= render 'users/follow_form', user: user %>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_user_info.html.erb
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-square pull-left profile-img", fallback: "no_image.png" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <th>following</th>
      <td>
        <%= link_to following_user_path(user) do %>
          <%= user.following.count %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>followers</th>
      <td>
        <%= link_to followers_user_path(user) do %>
          <%= user.followers.count %>
        <% end %>
      </td>
    </tr>
    <% unless user == current_user %>
      <tr>
        <th>
          <%= link_to 'chat room', chat_path(user.id), class: "chat" %>
        </th>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= render 'follows/unfollow', user: user %>
    <% else %>
      <%= render 'follows/follow', user: user %>
    <% end %>
  <% end %>
</div><br>

<div class="row">
  <%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>

app/views/users/_userinfo.html.erb
      <% if book.errors.any? %>
        <div id="explanation">
          <h3><%= book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-square pull-left profile-img", fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <td><%= user.name %></td>
          </tr>

          <tr>
            <th>introduction</th>
            <td><%= user.introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user) do %>
          <div class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></div>
        <% end %>
      </div>
      <h2>New book</h2>
      <%= form_for(book) do |f| %>

      <div class="field row">
        <%= f.label :Title %>
        <%= f.text_field :title, class: "col-xs-12 book_title" %>
      </div>

      <div class="field row">
        <%= f.label :Option %>
        <%= f.text_area :body, class: "col-xs-12 book_body" %>
      </div>

      <div class="actions row">
          <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
      </div>

      <% end %>
    </div>

app/views/users/edit.html.erb
<h2>User info</h2>
  <%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
		<div id="explanation">
			<h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
  <% end %>

    <div class="field">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>

    <div class="field">
			<%= f.label :Image %>
			<%= f.attachment_field :profile_image %>
    </div>

    <div class="field">
			<%= f.label :Introduction %>
			<%= f.text_area :introduction %>
    </div>

    <div class="actions">
			<%= f.submit "Update User" %>
    </div>

  <% end %>

app/views/users/followers.html.erb
<%= render 'follows/follow_users', users: @users %>

app/views/users/following.html.erb
<%= render 'follows/follow_users', users: @users %>

app/views/users/index.html.erb
<%= render 'layouts/sidebar', user: current_user, book: @book %>
  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-square pull-left profile-img", fallback: "no_image.png" %>
            </td>
            <td><%= user.name %></td>
            <%= render 'follows/follow_form', user: user %>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>

app/views/users/search.html.erb
<% if @user_or_book == "0" %>
  <%= render 'searches/search_users' %>
<% elsif @user_or_book == "1" %>
  <%= render 'searches/search_books' %>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/sidebar', user: @user, book: @book %>

<%= render 'books/index' %>

<% if @user == current_user %>
  <h2>Your MAP</h2>
  <% if @user.address_building.present? %>
    <div id='map' class="<%= @user.prefecture_code + @user.address_city + @user.address_street + @user.address_building %>"></div>
  <% else %>
    <div id='map' class="<%= @user.prefecture_code + @user.address_city %>"></div>
  <% end %>

  <style>
    #map {
      height: 400px;
    }
  </style>

  <script>
  /*
  mapを関数の外で定義(codeAddressでも使うため)
  geocoderを用意
  */

  let map
  let geocoder

  function initMap(){
    // geocoderを初期化
    geocoder = new google.maps.Geocoder()
    geocoder.geocode( { 'address': $('#map').attr('class')}, function(results, status) {
      if (status == 'OK') {
  　　　　　　　　　　　　// map.setCenterで地図が移動
        map.setCenter(results[0].geometry.location);

  　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });

    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -34.397, lng: 150.644},
    zoom: 8
    });
  }

  function codeAddress(){
    // 入力を取得
    let inputAddress = document.getElementById('address').value;

    // geocodingしたあとmapを移動
  }
  </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap">
  </script>
<% end %>