config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#home'
  get '/home/about', to: "homes#about"
  get '/search', to: 'users#search'
  get '/sort', to: 'books#index', as: :sort
  get 'chat/:id', to: 'chats#show', as: :chat
  get 'tags/:tag', to: 'books#index', as: :tag
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  acts_as_taggable

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Book.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "0"
        Book.where(['title LIKE ?', "#{search}"])
      elsif how_search == "1"
        Book.where(['title LIKE ?', "#{search}%"])
      elsif how_search == "2"
        Book.where(['title LIKE ?', "%#{search}"])
      elsif how_search == "3"
        Book.where(['title LIKE ?', "%#{search}%"])
      else
        Book.none
      end
    end
  end

  scope :ranking, -> { find(Favorite.group(:book_id)
                      .rank.limit(3).pluck(:book_id)) }
  scope :my_rank, -> (current_user) { find(Favorite.my_book(current_user)
                      .group(:book_id).rank.limit(3).pluck(:book_id)) }
  scope :all_rank, -> { find(Favorite.group(:book_id).rank.pluck(:book_id)) }
  scope :order_comment, -> { find(BookComment.group(:book_id).rank.pluck(:book_id)) }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_book, only: [:edit, :update]
  before_action :ranking_books

  def index
    if params[:submit_select]
      sort_books
    elsif params[:sort]
      @books = Book.order(sort_column + ' ' + sort_direction).page(params[:page])
    elsif params[:tag]
      @books = Book.tagged_with(params[:tag]).page(params[:page])
    else
      @books = Book.page(params[:page])
    end
    @book = Book.new
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_commets = @book.book_comments
    @user = User.find(@book.user_id)
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to @book
    else
      @user = current_user
      @books = Book.all.page(params[:page])
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :tag_list)
    end

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def correct_book
      @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
    end

    def sort_books
      case params[:submit_select]
      when "0"
        @books = Book.page(params[:page])
      when "1"
        @books = Book.order(created_at: :desc).page(params[:page])
      when "2"
        @books = Kaminari.paginate_array(Book.all_rank).page(params[:page])
      when "3"
        @books = Kaminari.paginate_array(Book.order_comment).page(params[:page])
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_detail.html.erb
<td>
  <%= link_to(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, class: "img-square profile-img", fallback: "no_image.png" %><br>
    <%= book.user.name %>
  <% end %>
</td>
<td><%= book.title %></td>
<td> <%= book.body %> </td>
<td><%= render 'books/tag', book: book %></td>
<td>
  <%= render 'favorites/hart_button', book: book %>
</td>
<td><i class="far fa-comment"><%= book.book_comments.count %></i></td>

<% if @book.user == current_user %>
  <td><%= link_to "Edit", edit_book_path(book), class: "btn-sm btn-success edit" %></td>
  <td><%= link_to "Destroy", book_path(book), method: :delete, data: { confirm: "本当に消しますか？"}, class: "btn-sm btn-danger destroy" %></td>
<% end %>

app/views/books/_index.html.erb
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th><%= sortable "title" %></th>
          <th><%= sortable "body", "Opinion" %></th>
          <th>Tag</th>
          <th><%= sortable "created_at", "date" %></th>
          <th></th>

          <% if controller.controller_name == "books" %>
            <th>
              <%= form_tag(sort_path, :method => 'get', id: "submit_form") do %>
                <%= select_tag(:option, options_for_select([["ーーーーー", "0"],["新着順", "1"],["人気順", "2"],["コメント順", "3"]]), id: "submit_select", name: "submit_select") %>
              <% end %>
            </th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr class="book_<%= book.id %>">
            <%= render 'favorites/favorites', book: book %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @books %>
  </div>
</div>

app/views/books/_new_book.html.erb
<%= form_for(book) do |f| %>

  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: "col-xs-12 book_title" %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: "col-xs-12 book_body" %>
  </div>

  <div class="field row">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, value: book.tag_list.join(','), "data-role" => "tagsinput", class: "col-xs-12" %>
  </div>

  <div class="actions row">
      <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
  </div>

<% end %>

app/views/books/_ranking.html.erb
<% if @ranking_books.empty? %>
  <p style="font-weight: bold;">ランキングがありません</p>
<% end %>
<table class="table">
  <% @ranking_books.each.with_index(1) do |book, i| %>
    <tr>
      <th><span class="ranking-<%= i %>"><%= i %>位</span></th>
      <td><%= link_to book.title, book_path(book) %></td>
    </tr>
  <% end %>
</table>

app/views/books/_tag.html.erb
<% book.tag_list.each do |tag| %>
  <%= link_to tag, tag_path(tag), class: "label label-primary" %>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= form_for(@book) do |f| %>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field row">
        <%= f.label :Title %>
        <%= f.text_field :title, class: "col-xs-12" %>
      </div>

      <div class="field row">
        <%= f.label :Opinion %>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>

      <div class="actions row">
        <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
      </div>
    <% end %>

    <%= link_to "Show", @book %>
    |
    <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/sidebar', user: current_user, book: @book %>

<%= render 'books/index' %>

app/views/books/show.html.erb
<%= render 'layouts/sidebar', user: @book.user, book: @new_book %>
<%= render 'book_comments/comment_error' %>


  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table">
    <tbody>
      <tr class="book_<%= @book.id %>">
        <%= render 'books/detail', book: @book %>
      </tr>
    </tbody>
    </table>

    <h2>Comments</h2>
    <table class="table comment_<%= @book.id %>">
      <%= render 'book_comments/comment', book_comments: @book.book_comments %>
    </table>

<%= form_with model:[@book, @book_comment], data: {remote: true} do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows: '5', class: "form-control" %>
      <%= f.submit "送信", class: " pull-right" %>
    </div>
  </div>
<% end %>
</div>