config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#home'
  get '/home/about', to: "homes#about"
  get '/search', to: 'users#search'
  get '/sort', to: 'books#index', as: :sort
  get 'chat/:id', to: 'chats#show', as: :chat
  get 'tags/:tag', to: 'books#index', as: :tag
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  def search
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_books.html.erb
<h2>Books search</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th>Date</th>
      <th></th>
      <th>
        <%= form_tag(sort_path, :method => 'get', id: "submit_form") do %>
          <%= select_tag(:option, options_for_select([["ーーーーー", "0"],["新着順", "1"],["人気順", "2"],["コメント順", "3"]]), id: "submit_select", name: "submit_select") %>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr class="book_<%= book.id %>">
        <%= render 'favorites/favorites', book: book %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/searches/_search_form.html.erb
<% if user_signed_in? %>
  <div class="row search">
    <div class="col-xs-7 col-xs-offset-5">
      <%= form_tag(search_path, :method => 'get') do %>
        <%= text_field_tag :search %>
        <%= select_tag(:option, options_for_select([["user", "0"],["book", "1"]])) %>
        <%= select_tag(:choice, options_for_select([["完全一致", "0"],["前方一致", "1"],["後方一致", "2"],["部分一致", "3"]]))%>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/searches/_search_users.html.erb
<h2>Users search</h2>
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th colpsan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @users. each do |user| %>
    <tr>
      <td>
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, class: "img-square pull-left profile-img", fallback: "no_image.png" %>
        <% end %>
      </td>
      <td><%= user.name %></td>
      <%= render 'follows/follow_form', user: user %>
      <td><%= link_to "Show", user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>