config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#home'
  get '/home/about', to: "homes#about"
  get '/search', to: 'users#search'
  get '/sort', to: 'books#index', as: :sort
  get 'chat/:id', to: 'chats#show', as: :chat
  get 'tags/:tag', to: 'books#index', as: :tag
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resource :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :chats, only: [:create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/_error_messages.html.erb
<% if book.errors.any? %>
  <div id="explanation">
    <h3><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
  <nav class="container">
    <div class="nav navbar-nav navbar-left">
      <span class="headline">Bookers</span>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to " Home", user_path(current_user.id),
          class: "glyphicon glyphicon-home" %></li>
      <li><%= link_to " Users", users_path,
          class: "glyphicon glyphicon-user" %></li>
      <li><%= link_to " Books", books_path,
          class: "glyphicon glyphicon-book" %></li>
      <li><%= link_to " logout", destroy_user_session_path,
          method: :delete, class: "glyphicon glyphicon-log-out" %></li>
      <% else %>
      <li><%= link_to "  Home", root_path,
          class: "glyphicon glyphicon-home" %></li>
      <li><%= link_to " About", home_about_path,
          class: "glyphicon glyphicon-link" %></li>
      <li><%= link_to " sign up", new_user_registration_path,
          class: "glyphicon glyphicon-edit" %></li>
      <li><%= link_to " login", new_user_session_path,
          class: "glyphicon glyphicon-log-in" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<%= render 'layouts/error_messages', book: book %>

  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= render 'users/user_info', user: user %>

      <h2>New book</h2>
      <%= render 'books/new_book', book: book %>

      <% if current_page?(user_path(current_user)) %>
        <span class="my-ranking"><%= current_user.name %>'s</span>
      <% end %>
      <h2>Book rank</h2>
      <%= render 'books/ranking' %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container">

    <%= render 'searches/search_form' %>


    <p id="notice"><%= notice %></p>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</body>

</html>